[package]
name = "sync-tests"
version = "0.1.0"
edition = "2021"
publish = false

[[bench]]
name = "durable-writes"
harness = false

[dependencies]
rand = "0.8"
libc = "0.2.126"

[dev-dependencies]
tempfile = "3.3.0"
criterion = "0.3.5"
tabled = "0.7.0"
